# Generated by Django 3.2.5 on 2021-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('PT', 'Part Time'), ('FT', 'FULL TIME')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
